CREATE DATABASE IF NOT EXISTS ecofarm;
USE ecofarm;

CREATE TABLE farms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farm_size DECIMAL(10,2) NOT NULL,
    crop_type VARCHAR(100) NOT NULL,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
